# Generated by Django 2.1.7 on 2019-03-24 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Коментар')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('moderation', models.BooleanField(default=False)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='Новина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Коментатор')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='new',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
