# Generated by Django 2.1.7 on 2019-03-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190325_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Картинка'),
        ),
    ]
